Repository subramanian-elavathur/tici-taca-toey-web, pull requests merged in 2020-07, with the labels that each got.

#21 Update Copyright Details
  LICENSE
Labels: bug

#23 Simplifying Cell Component Props
  src/features/game/board/Board.tsx
Labels: enhancement

#24 integrating win seq length with UI
  src/common/model.ts
  src/features/start/Start.tsx
  src/redux/actions.ts
Labels: enhancement, good first issue

#25 Hightlighting winning sequence
  src/features/game/board/Board.tsx
Labels: enhancement, good first issue, help wanted
